#!/usr/bin/env python3
"""Regenerates Sources/Chrome/AppIcon.swift from Assets/AppIcon/.

The build produces a single swiftc binary with no resource bundle, so
the app icon and the menu-bar template are embedded as base64, mirroring
tools/gen_agent_icons.py.

Inputs:
- app-icon.png           1024x1024 master; sips (builtin) rasterizes the
                         smaller Dock/menu sizes at generation time.
- menubar-template@2x.png  template glyph for the NSStatusItem button.

To refresh, drop new PNGs into Assets/AppIcon/ and rebuild.
"""

import base64
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "Assets" / "AppIcon"
TARGET = ROOT / "Sources" / "Chrome" / "AppIcon.swift"

MASTER = ASSETS / "app-icon.png"
ICON_SIZES = (1024, 512, 256, 128, 64, 32, 16)
TEMPLATE = ASSETS / "menubar-template@2x.png"


def rep_bytes(size: int) -> bytes:
    """The PNG bytes for one icon edge length (master for 1024)."""
    if size == 1024:
        return MASTER.read_bytes()
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / f"{size}.png"
        subprocess.run(
            ["sips", "-z", str(size), str(size), str(MASTER), "--out", str(out)],
            check=True, capture_output=True)
        return out.read_bytes()


def main() -> None:
    if not MASTER.is_file():
        raise SystemExit(f"missing {MASTER}")
    if not TEMPLATE.is_file():
        raise SystemExit(f"missing {TEMPLATE}")

    icon_reps = []
    for size in ICON_SIZES:
        b64 = base64.b64encode(rep_bytes(size)).decode()
        icon_reps.append(f'        ({size}, "{b64}"),')

    template_b64 = base64.b64encode(TEMPLATE.read_bytes()).decode()

    swift = f'''import AppKit
/// GENERATED by tools/gen_app_icon.py — do not edit by hand.
/// Regenerate: python3 tools/gen_app_icon.py (or just build).

enum AppIcon {{
    /// App-icon PNGs as [pixel edge, base64] pairs, largest first.
    /// The 1024px master came straight from the asset; smaller sizes
    /// were rasterized from it by sips at generation time.
    static let iconPNGs: [(Int, String)] = [
{chr(10).join(icon_reps)}
    ]

    /// Menu-bar glyph (already black-on-transparent; isTemplate renders
    /// it with the system appearance).
    static let menuBarTemplatePNG = "{template_b64}"

    /// Multi-rep application icon: AppKit picks the nearest pixel size
    /// for Dock / ⌘Tab / About without resampling on screen.
    static var image: NSImage {{
        let image = NSImage(size: NSSize(width: 1024, height: 1024))
        for (pixels, b64) in iconPNGs {{
            guard let data = Data(base64Encoded: b64),
                  let rep = NSBitmapImageRep(data: data) else {{ continue }}
            rep.size = NSSize(width: pixels, height: pixels)
            image.addRepresentation(rep)
        }}
        return image
    }}

    static var menuBarTemplate: NSImage? {{
        guard let data = Data(base64Encoded: menuBarTemplatePNG),
              let image = NSImage(data: data) else {{ return nil }}
        image.isTemplate = true
        return image
    }}
}}
'''
    TARGET.write_text(swift)
    print(f"AppIcon.swift: {len(ICON_SIZES)} icon reps + menu-bar template")


if __name__ == "__main__":
    main()
